DROP TABLE DEV_QUIZ_HEADER;

CREATE TABLE DEV_QUIZ_HEADER (QUIZ_NUMBER varchar(255),QUIZ_NAME varchar(120),QUIZ_CREATOR_ID varchar(255),QUIZ_GENRE varchar(120),DATE_CREATED timestamp DEFAULT CURRENT_TIMESTAMP,DATE_LAST_EDITED timestamp NULL DEFAULT NULL,PASS_PERCENTAGE decimal(10,10),IS_DELETED tinyint(1),DATE_DELETED timestamp NULL DEFAULT NULL,HIGHEST_QUESTION_NUMBER int(11) DEFAULT 0,PRIMARY KEY(QUIZ_NUMBER));


DROP TABLE DEV_QUIZ_QUESTION;


CREATE TABLE DEV_QUIZ_QUESTION (QUIZ_NUMBER varchar(255) NOT NULL,QUESTION_NUMBER int(100),MUSIC_SOURCE_URL varchar(255),ANSWER_1 varchar(255),ANSWER_2 varchar(255),ANSWER_3 varchar(255),ANSWER_4 varchar(255),CORRECT_ANSWER int(11),HINT varchar(255),DATE_CREATED timestamp DEFAULT CURRENT_TIMESTAMP, IS_DELETED tinyint(1) DEFAULT 0, DATE_DELETED  timestamp NULL DEFAULT NULL)



DROP TABLE DEV_QUIZ_HISTORY

CREATE TABLE DEV_QUIZ_HISTORY_HEADER (QUIZ_HISTORY_NUMBER varchar(255),QUIZ_NUMBER varchar(255),QUIZ_CREATOR_NUMBER varchar(255),QUIZ_COMPLETER_NUMBER varchar(255),DATE_COMPLETED timestamp NULL DEFAULT NULL,TOTAL_QUESTIONS int(100),TOTAL_QUESTIONS_CORRECT int(100),SCORE decimal(10,10),IS_PASSING tinyint(1);


CREATE TABLE DEV_QUIZ_HISTORY_QUESTION (QUIZ_HISTORY_NUMBER varchar(255),QUIZ_NUMBER varchar(255),QUESTION_NUMBER int(100),MUSIC_SOURCE_URL varchar(255),ANSWER_1 varchar(255),ANSWER_2 varchar(255),ANSWER_3 varchar(255),ANSWER_4 varchar(255),ANSWER_CHOSEN int(11), CORRECT_ANSWER int(11),DATE_COMPLETED timestamp NULL DEFAULT NULL);